version: '3'
services:
  prestashop:
    image: jjayjohnny/be_188679
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
    ports:
      - 18868:443
    environment:
      DB_SERVER: db
      DB_NAME: BE_188679
      DB_USER: root
      DB_PASSWD: student
      PS_DOMAIN: localhost:8080
      PS_FOLDER_ADMIN: admin2137
      PS_FOLDER_INSTALL: install2137
      PS_INSTALL_AUTO: 1
      PS_LANGUAGE: pl
      PS_COUNTRY: PL
      PS_DEV_MODE: 1
    
    networks: 
      - admin-mysql_default
