services:
  prestashop:
    image: jjayjohnny/be_188679:latest
    user: root
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    ports:
      - 18868:443
    environment:
      DB_SERVER: db
      DB_NAME: BE_188679
      DB_USER: root
      DB_PASSWD: student
      PS_FOLDER_ADMIN: admin2137
      PS_FOLDER_INSTALL: install2137
      PS_INSTALL_AUTO: 1
      PS_LANGUAGE: pl
      PS_COUNTRY: PL
      PS_DEV_MODE: 1
    networks:
      - admin-mysql_default
      - be_188679_network
  
  memcached:
    image: memcached
    user: 1000:1000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - be_188679_network

networks:
  be_188679_network:
  admin-mysql_default:
    external: true