<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW5yxeJm\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW5yxeJm/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerW5yxeJm.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerW5yxeJm\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerW5yxeJm\appAppKernelProdContainer([
    'container.build_hash' => 'W5yxeJm',
    'container.build_id' => '8f14cf42',
    'container.build_time' => 1697058492,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW5yxeJm');
